panther-labs/pounce

.github/CODEOWNERS, .github/pull_request_template.md, AUTHORS, CONTRIBUTING.md, LICENSE, README.md
Additional files needed for OSS contributions. 
- AUTHORS CONTRIBUTING, LICENSE files
- README tune
- Add myself as a CODEOWNERS as backup
- None needed
=> [repo] AUTHORS, LICENSE, CONTRIBUTING files

.circleci/config.yml, src/components/BaseButton.tsx, src/components/IconButton.tsx
Makes sure to automatically create versions on master pushes 
- Add semantic-release on master pushes
- Merging this to master should automatically create a new release ^^
=> CI: Update CircleCI config

src/components/BaseButton.tsx
add default (missing) type="button" to all buttons so they don't submit any form by mistake
=> fix(button): add type attr

src/themes/default.ts
Add missing colors
- Update theme
- none
=> fix(theme): add extra colors

LICENSE, README.md, package-lock.json
Just some Friday evening code pushes
- Standardize our repos to Apache-2.0
- Update package dependencies to resolve vulnerability
- None
=> License Change + Package Update

.github/CODEOWNERS
Add Alex to CODEOWNERS
- Add Alex to Codeowners
- Notify Jack on `.md` changes only
- N/A
=> chore(CODEOWNERS): add alex

.circleci/config.yml
Upgrade Node in CI/CD to latest stable
- Bump CircleCI Node docker image
- N/A
=> build: bump node version in circleci

src/components/Button/utils.ts
High level overview here
- Describe changes here
=> fix: hover bg for Button

.github/CODEOWNERS
Add Theodore to repo codeowners
- Self explanatory
- N/A
=> chore: add Theodore to code-owners

src/theme/colors.ts
Remove duplicates and align the white palette.
=> fix: align white color pallette and remove duplicates

styleguide.config.js
Ignore test files from styleguist building process
=> Fix styleguist ignore pattern

jest/setup.ts, src/components/Box/Box.test.tsx, src/components/Box/__snapshots__/Box.test.tsx.snap
Fix `jest-emotion` snapshot serializer by adding a dummy emotion style.
=> Fix jest emotion serializer

src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Update failing snapshot tests.
=> test: update snapshot tests for Tabs

src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.test.tsx, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Add icon support for `<TextInput />` component.
- Add icon renderer with the same principles as the 
- Added snapshot coverage.
=> feat: add icon support for TextInput component

src/components/DateInput/__snapshots__/DateInput.test.tsx.snap, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.test.tsx, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Drilling down the icon props used for styling.
- Manually and visullay
=> feat: add iconProps for TextInput

src/components/DateInput/Day.tsx, src/components/DateInput/Month.tsx, src/components/DateRangeInput/DateRangeInput.mdx, src/components/DateRangeInput/DateRangeInput.test.tsx, src/components/DateRangeInput/DateRangeInput.tsx, src/components/DateRangeInput/Presets.tsx, src/components/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap
When value is empty there was a weird highlighting issue with the selected dates. This one parses just the values provided without fallbacks for new values.
- Visually and manually
=> Fix: daysjs parsing dates for DateRangeInput

src/components/DateInput/DateInput.mdx, src/components/DateInput/DateInput.test.tsx, src/components/DateInput/DateInput.tsx, src/components/DateInput/__snapshots__/DateInput.test.tsx.snap, src/components/DateRangeInput/DateRangeInput.mdx, src/components/DateRangeInput/DateRangeInput.test.tsx, src/components/DateRangeInput/DateRangeInput.tsx, src/components/DateRangeInput/DoubleTextInput.tsx, src/components/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap, src/components/DateRangeInput/__snapshots__/DoubleTextInput.test.tsx.snap, src/components/TextArea/TextArea.mdx, src/components/TextArea/TextArea.test.tsx, src/components/TextArea/TextArea.tsx, src/components/TextArea/__snapshots__/TextArea.test.tsx.snap, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.test.tsx, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap, src/components/utils/Input/InputControl.test.tsx, src/components/utils/Input/InputControl.tsx, src/components/utils/Input/InputLabel.tsx, src/components/utils/Input/__snapshots__/InputControl.test.tsx.snap
In order to align with our redesign need, we shall accommodate a few enhancements for our input components.
- Add icon alignment for `TextInput`
- Add `variant="solid"` for TextInput, Textarea, DateInput and DateRangeInput components
https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/39dcb3e2-1e72-49b2-afab-3a59c8459f66/commits/fc0e3669ae46aad9ff03e270ad13f07d58e1b9b9/files/aaef24b5-d84a-463f-a022-764fae94ca58/layers/4D9D942C-F607-41F5-8623-E2B6D9FD1D19
- Unit tests.
=> Input enhancements

src/theme/colors.ts
Missing `navyblue-350` color per Jim suggestion
- Added `navyblue-350` color
=> chore: added navyblue-350 color

src/components/Combobox/Combobox.mdx, src/components/Combobox/Combobox.tsx, src/components/DateRangeInput/DateRangeInput.tsx, src/components/DateRangeInput/DoubleTextInput.tsx, src/components/MultiCombobox/MultiCombobox.mdx, src/components/MultiCombobox/MultiCombobox.test.tsx, src/components/MultiCombobox/MultiCombobox.tsx, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap
Added "solid" variant for Combobox and MultiCombobox, also added a small fix for DateRangeInputProps as TS is complaining.
=> Fix Combobox variant

src/components/MultiCombobox/MultiCombobox.mdx, src/components/MultiCombobox/MultiCombobox.test.tsx, src/components/MultiCombobox/MultiCombobox.tsx, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap
It was requested to have the option to clear all items in `MultiComboBox`. I added this option to be display only when at least 6 items are added to the combobox.
- Added an AbstractButton displayed conditionally
- Added tests for functionality
- Locally & visually
=> feat: added AbstractButton that provides the ability to clear all items

src/components/MultiCombobox/MultiCombobox.tsx, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap
closes https://app.asana.com/0/1199975676341842/1199936728416968
This PR changes the way we render the `TextInput` in multi select `Dropdowns`, in order to keep the `TextInput` in the same line as the `Tags` and only move to a separate line when the user's input can't fit in the existing line anymore.
https://user-images.githubusercontent.com/15084305/109520818-4b8af800-7ab5-11eb-95dc-96144576c536.mov
- Locally
=> feat: inline MultiComboBox input field

.github/workflows/asana.yml
Related to: https://app.asana.com/0/1199942399745175/1199956320184289/f
- Added asana.yml to pounce
=> feat: Asana GH actions

src/components/DateInput/__snapshots__/DateInput.test.tsx.snap, src/components/DateRangeInput/__snapshots__/DoubleTextInput.test.tsx.snap, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap, src/components/TextArea/__snapshots__/TextArea.test.tsx.snap, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.test.tsx, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap, src/components/utils/Input/InputControl.tsx, src/components/utils/Input/InputElement.tsx, src/components/utils/Input/__snapshots__/InputControl.test.tsx.snap
Add support for prefix within the text input components.
https://user-images.githubusercontent.com/1022166/111817114-48ca3880-88e6-11eb-8867-08aa50c5cbc1.mov
- Add support and fix the Text Input component 
- Add and fix snapshot testing.
=> Prefix for TextInput

package-lock.json, package.json
Bump `path-parse` package via preinstall script
- Added resolutions -> `path-parse: ^v1.07`
- Install path-parse on my main branch
=> fix: bump path-parse

package-lock.json, package.json
Modify directly package-lock.json for `path-parse`
- Revert the previous merge
- Modified package-lock directly
- Installed branch on panther repo
=> fix: path-parse update on package-lock

src/components/DateInput/__snapshots__/DateInput.test.tsx.snap, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.test.tsx, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
When subdomains are in place we need to support a `suffix` for input text.
=> Add suffix for text input

src/components/Alert/Alert.mdx, src/components/Snackbar/Snackbar.tsx, src/components/utils/ControlledAlert/ControlledAlert.tsx
Modify default alert props
-  Modify default alert props
- manually
=> Modify default alert props

src/components/Card/Card.tsx, src/components/Card/useCardVariantBackground.tsx
Add more Card color options
- Added lighter and darker card variants
- manually
=> Additional card color variants

.github/CODEOWNERS
Add @georgesimos to CODEOWNERS
- Add @georgesimos to CODEOWNERS
- N/A
=> Chore: add George Simos to CODEOWNERS

src/theme/colors.ts
The design team would like us to support a font color of navyblue-900 (#0A0F1A).
- Adds navyblue-900 to colors constant
=> feat: support navyblue-900 color
