src/components/BaseBadge.tsx, src/components/Combobox.tsx, src/components/MultiCombobox.tsx, src/components/Table.md, src/components/Table.tsx, src/components/Tooltip.md, src/components/Tooltip.tsx, src/utils/useEnumerableTableRows.tsx, src/utils/useSelectableTableRows.tsx
The `hoverDelay` should not be a required prop since it should be more transparent to the basic user
- Make `hoverDelay` an optional prop
- Allow the value of items in a table to have `any` type (to align with every type of data that the user has)
- `BadgeProps` now extends `BaseTextProps` in order not to require the `size` prop from the Text component
- Enhance docs on `Table` component
- Add generics to `Table`
- Rename generic prop in `Combobox` and `MultiCombobox`
- Typescript should not complain if you don't specify a `hoverDelay` on a `<Tooltip />` component
=> make Tooltip's `hoverDelay` optional

.circleci/config.yml, .commitlintrc.json, .huskyrc, .releaserc, CHANGELOG.md, CHANGELONG.md, package-lock.json, package.json, src/components/BaseButton.tsx, src/components/IconButton.tsx, src/components/ProgressBar.md, src/components/ProgressBar.tsx, src/index.tsx
TLDR; Re-write code in a more simpler way to create better TS definitions.
**Long Version**
This PR simplifies the use of the `styled` API (imported from `@emotion/styled`) in order to simplify the TS declarations that get created.
Currently, the `rollup` plugin that we use for creating the TS declaration files has a few hardcoded TS configurations. One of them is `noResolve` which would normally remove any `XXX.d.ts` references (added as triple-slash imports) from the built TS declarations of `pouncejs`. Unfortunately, this plugin forces references to be added to files using a wrong path. This causes all TS checks to fail when `skipLibCheck` is not present tin libraries that install `pouncejs`. 
This PR fixes that by changing the way code is writen so these references don't need to be …
=> Remove complex styled components

src/components/Combobox.tsx
the value of the input text was only updated when user was performing some actions and not when the whole external value props changed (i.e. cause of a re-render with different values)
=> fix(combobox): show input text updates on external value changes

src/components/BaseButton.tsx
this is to protect against links disguised as buttons
=> fix(basebutton): add `text-decoration: none` to all

.eslintrc, package-lock.json, package.json, src/components/Table.md, src/components/Table.tsx
Currently the only visually separate a table's rows is through a different bg. This PR also adds the option to separate them through a light border so that the bg can change the same
- Deprecate `alternateBg` prop in Table. Add `rowSeparationStrategy`
=> feat(table): add `rowSeparationStrategy` prop

.releaserc
This PR adds NPM plugin to the releasing process, so we can install pounce from NPM as well
- Add npm to semantic release plugins
- Local
=> build(npm): add npm releases

package.json
Package should be publicly accessible
-  Mark pkg as public in `package.json`
- N/A
=> fix: mark pkg as public

src/components/Combobox/Combobox.tsx
ComboBox seems to not support [`true`,`false`] values. We use this on filtering policies `Auto-remediation Status` and selecting the `false` value has no effect!
- Updated check value on ComboBox
=> Fix for ComboBox for value === false

src/components/AbstractButton/AbstractButton.mdx, src/components/Alert/Alert.mdx, src/components/Alert/Alert.tsx, src/components/Snackbar/Snackbar.tsx, src/components/Snackbar/SnackbarContext.tsx
Currently, Alert accepts all kinds of props which makes it hard to reason about when it comes to what it "can" and "cannot" do. 
This PR restricts the alert props to its native ones, dissallowing to add props which would be (up until now) forwarded to the underlying Card component 
- Add `size` prop
- Restrict Alert types
- Tested on docs page
=> Restrict Alert module

src/components/Box/system.ts, src/components/utils/Input/index.tsx
Some commits didn't go through a PR so any ESLint/Prettier/TS issues slipped in. This PR remediates that
- Run `prettier --write`
- Add `eslint-disable` on a particular line
- CI is passing
=> build: fix ESLint issues with CI

package-lock.json, package.json, src/components/Collapse/Collapse.tsx, src/components/Snackbar/SnackbarContext.tsx
As `react-use-measure` [docs](https://github.com/react-spring/react-use-measure/#%EF%B8%8F-notes) suggest the hook requires a polyfill in order to properly work with Safari. The repo was not properly working and the webpack error tracking was complaining on startup. This PR adds the polyfill as suggested.
- Add the [juggle/resize-observer](https://github.com/juggle/resize-observer) as suggested to `package.json` and `package-lock.json`
- Patch the `useMeasure` React hook to consume the polyfill 
- Check out the master branch, run `npm i` and `npm run start`
- Open the app in Safari (I am currently using the version 13.0.5 which does not support the [resize observer](https://caniuse.com/#feat=resizeobserver)
- Check out the PR branch, once more run run `npm i` and `npm run start`
- The …
=> Fix safari intersection observer polyfill dependency

src/components/utils/Input/InputElement.tsx
Having `border: none` messed up with height measurements  in jsdom. Making it be `0` fixes that.
- Change `border: none` to `border: 0`
- N/A
=> fix: issue with JSDom and TextAreaAutosize

package-lock.json, package.json, src/components/Table/Table.mdx
Fixes issue with vulnerable dependency of `lodash-se`
- Replace `lodash-es` with `lodash`. Bump cascading deps to latest patch version
- `npm audit  --production`
=> CI: fix  lodash vulnerability

src/components/Box/Box.mdx, src/theme/theme.ts
Pounce had a single breakpoint for small & large screens. Adding a new one for large-mobiles & tablets in an effort to help with responsiveness
- Add new breakpoints to pounce's default theme
- Through docs & examplees
=> Feat: add new default breakpoints  to pounce

src/components/IconButton/IconButton.mdx, src/components/IconButton/IconButton.tsx, src/components/IconButton/useIconButtonStyles.tsx
Adds a new style to  `IconButton`  to align with the design needs
- add same `outline` styling as the `Button` already has
https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/commits/d4746ddd93986a63d5e9fd960cccbd3e2acd2db8/files/3cc6ad23-a286-4d07-a10b-a9852419c176/layers/C8D76341-DF55-4723-A268-27B7FB3B5D70?collectionId=bf397f88-46df-4162-ba27-ae65dae0f98c&collectionLayerId=a25bc457-e96c-4525-98a6-b3e762c2b9f5&mode=design
- N/A, Can be seen at `{DOCS_URL}/#/IconButton`
=> Feat: add `outline` style for `IconButton`

src/components/NumberInput/NumberInput.mdx, src/components/NumberInput/NumberInput.tsx, src/utils/helpers.ts
Since the `<input type="number" />` does not properly handle the `onChange` events when [`HTMLInputElement.stepUp`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepUp) or [`HTMLInputElement.stepDown`](HTMLInputElement.stepDown) methods are getting invoked we need to make the actual component controlled, thus we need to create a custom callback. 
- Added `onInputNumberChange` for `NumberInput` component.
- Manually and visually through `styleguidist`
=> Fix: Input number proper `onChange` event

src/theme/colors.ts
As described added 3 missing colors as designed. No side-effects introduced.
=> fix: add missing colors for pounce theme

src/components/Tabs/TabList.tsx, src/components/Tabs/TabPanel.tsx, src/components/Tabs/index.tsx, src/components/Tabs/useTabStyles.tsx
Currently tabs are not "outlined" when a user users the `<tab>` key. At the same time, when you tab, the entire tabpanel gets focused which you probably don't want that.
This PR fixes that by making sure focus is handled correctly. Also it  adds a missing border below the tabs (SS)
Problematic focusing can be seen here
A new border has been added 
- Add border
- Re-instate tab outline
- Remove tab panel focus
- Visual
=> Fix issues with tab focuses

src/components/Tabs/Tab.tsx
This  PR fixes  an issue where the internal & private `index` prop that's given automatically to a `Tab` element through it's `TabList` parent, was **also** explicitly required by the user
- Fix TS typings, by adding internal types
- N/A
=> fix: typescript typings for the `Tab` element

src/components/Modal/Modal.tsx
When we have complex content (somethign other than just a text) in the Modal's header, the close button is sitting behind it and can't be clicked. This PR fixes that  byy making sure that the modal's button is always in the front
- Add `zIndex: 1` to modal's close button container
- Manual
=> fix: add zIndex to modal's close button

src/components/Link/useLinkStyles.tsx
Users have complained that the color of the link is not easy to read given the "dark" background that it normally sits on. This prompted our designs to change in order to lighten the colors of the links
https://app.abstract.com/projects/ab14d6c7-511b-4577-8de9-25ca9cd2918b/branches/master/commits/adef37090241a6512e10d5d9cbd9688409fc076f/files/80211ea4-8009-417c-883f-6c096a2959bb/layers/008E0080-642C-4F61-9632-19A8CFD0E76D?mode=build&selected=root-A9FEF646-EAB4-4A36-91B7-FBFF9BBDE29C
- Change link colors
- Visual
=> fix: link color according to latest design lib updates

babel.config.js, package-lock.json, package.json, src/components/Badge/__snapshots__/Badge.test.tsx.snap, src/components/Box/Box.tsx, src/components/Box/__snapshots__/Box.test.tsx.snap, src/components/Box/system.ts, src/components/Flex/__snapshots__/Flex.test.tsx.snap, src/components/Flex/utils.tsx, src/components/PseudoBox/PseudoBox.tsx, src/components/Table/TableRow.tsx, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR removes emotioon's babel plugin tthat allows  components to specify a `css` prop and replaces it with a similar `sx` prop. The benefits of that are:
-  `css` prop added 1 `<CSSPropInternal>` React element to the component tree of each pounce element, which has now  been  removed. This will improve performance,  since React will have to manage way fewer components
- `css` prop accepts regular CSS & needed  additional configuration to make theming  work,  while `sx` automatically accepts theme-aware props
- `sx` prop has a simple object-like API, where as `css` had a more complex one (see code below)
- Styled-system prop transformations are now handled internally in `sx`, allowing us to delete a lot of custom code
- Remove un-needed babel preset
- Globally replaced `css` with `sx` …
=> refactor: Replace `css` prop with `sx` prop

src/components/Combobox/Combobox.mdx, src/components/Combobox/Combobox.tsx, src/components/MultiCombobox/MultiCombobox.mdx, src/components/MultiCombobox/MultiCombobox.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap, src/components/utils/Input/InputElement.tsx, src/components/utils/Input/InputLabel.tsx, src/components/utils/Menu/Menu.tsx
Due to the design of the DateInput component, we have some combo boxes without any labels attached. This PR allows the creation of such visual effects.
- Introduce a new prop called `standalone` which allows the input elements to work just with the placeholder text.
=> fix: Input labels

src/components/Box/Box.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap, src/components/utils/Input/InputElement.tsx, src/components/utils/Input/InputLabel.tsx, src/system/utility.ts
This PR adds a `visuallyHidden` prop  to the `Box` component. This hides the  `<Box>` from the UI, while still allowing screen readers to read it
- Add `visuallyHidden` prop & remove its re-declaration in `InputLabel`
- Make standalone `InputElement` look visually like the typical `InputElement`
After the changes they look more similar (notice font color & font weight) :
=> Feat visually hidden

jest/utils/render.tsx, src/components/MultiCombobox/MultiCombobox.test.tsx, src/components/MultiCombobox/MultiCombobox.tsx, src/components/MultiCombobox/Tag.tsx, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap
One of the downsides of using MultiCombobox when expecting custom input is that people rarely realize that they need to press "Enter" to save it. In addition, people rarely realize that pressing "Enter" allows them to add more values & when using "pasted" data, that creates problems since their value is lost on blur.
This PR adds UX updates to make their life easier:
- Makes sure to automatically select custom (user entered) values on blur
- Makes sure to automatically tokenize a pasted value containing newlines or commas
- Allows `,`  to be used in the same way as `Enter`
- Modify behavior of MultiCombobox
- Make sure to show always render placeholder text
- Add minor accessibility attributes
- Add tests to MultiCombobox
We don't automatically convert single-pasted items …
=> Enhance MultiCombobox UX

src/components/Collapse/Collapse.tsx
Currently when something is animating, the items "behind" the animation are not clickable until the animation finishes. In cases where the item gets removed from the screen, you see it disappearing but UI behind it is still not clickable until the animation finishes.
This gets fixed by  adding `pointer-events: none` to the item that's "disappearing"
- Instantly add `pointer-events: none` to the animating item
=> fix: make sure collapse animation doesn't hinder clicking

src/components/Table/TableRow.tsx
Currently, when a row is  `selected`, its styles get trumped (pun intended) from the `:hover` ones. This PR makes sure that CSS rules don't overlap each other
- Properly assign CSS rule styles for  `<TableRow selected />`
- Update `selected` color according  to latest designs
=> fix: issue with `selected` row on Table

README.md, src/components/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap, src/components/Icon/Icon.tsx, src/theme/customIcons.ts, src/theme/theme.ts
Currently, pounce allows  you  to have custom icon definitions, by overriding the `icons` prop in the `theme` that gets passed  to  the `ThemeProvider`. 
So far though, you'd always be getting an invalid TS error, stating that this icon doesn't exist. To fix that, pounce now exposes a `CustomIcons` type which you can override locally in your project (using a local declaration file) in order to extend the set of known `icon`  keys that Pounce is aware of.
- Make sure all icon keys are taken from `Theme`
- Export an empty `CustomIcons` interface in order to allow overrides
- Update docs
- Installed it in a project and managed to get it working  on external projects by following the README instructions
=> feat: allow custom typing extension to support custom icons

package-lock.json, package.json, src/components/DateInput/DateInput.test.tsx, src/components/DateRangeInput/DateRangeInput.test.tsx
Since presets are dynamically generated using the current date snapshots are failing, thus we need to mock the global `Date` constructor. More info about the `dayjs` implementation can be found [here](https://github.com/iamkun/dayjs/issues/500)
=> Fix global date mocks for time related specs

src/components/utils/ControlledAlert/useAlertStyles.tsx
Lot of people have complained that  our "X" icon looks like a button and they attempt to click it. With this in mind, the alert error style, will use an "!" icon  that will not confused users.
- Replace "X" icon with "!"
- N/A
=> fix: change `X` icon to `!` on the alert "error"

__mocks__/react-spring.ts, jest/setup.ts, jest/utils/helpers.ts, jest/utils/index.ts, package.json, src/components/Dropdown/DropdownMenu.tsx, src/components/Popover/Popover.mdx, src/components/Popover/Popover.test.tsx, src/components/Popover/Popover.tsx, src/components/Popover/PopoverContent.tsx, src/components/Popover/PopoverTrigger.tsx, src/components/Popover/__snapshots__/Popover.test.tsx.snap, src/components/Popover/index.tsx, src/components/Popover/usePopoverContentAlignment.tsx, src/index.tsx, src/utils/useDisclosure.tsx, src/utils/useEscapeKey.tsx, src/utils/useOutsideClick.tsx
This PR introduced a `Popover` component, which is part of a compound component family, comprising of:
- `Popover`: a wrapper (like `Dropdown`) that manages the state and decides what's shown and what's not
- `PopoverTrigger`: a trigger element (like `DropdownButton`) which acts as the trigger of the popover
`PopoverContent`: the actual popover that gets rendered
- Allow `Popover` to render as initially visible
- Allow `PopoverMenu` to have custom positioning
- Allow `offset` distance between the trigger and the popover
- Toggle popover on trigger click
- Toggle popover on trigger <Enter> keypress
- Close popover on click outside
- Close popover on ECS key press
- Move focus to popover as soon as its opened
- Accept render props components, exposing its internal state
- Adds Popover …
=> Feat: Popover component

src/components/MultiCombobox/MultiCombobox.test.tsx, src/components/MultiCombobox/MultiCombobox.tsx
This PR fixes some edge cases where proper input validation & sanitization was not enforced. Specifically, empty content was not allowed when entering a value manually, but was allowed during pasting. 
With this PR validation gets a bit more streamlined and makes sure that edge cases like that don't occur
- Run all user item additions through the same validators, regardless of whether they were added/pasted/blurred
- Extend `validateAddition` by passing `value` to allow users to define a function outside of React
- Make sure that empty or falsy values are always disallowed
=> fix: MultiCombobox validation issues

src/components/DateInput/Month.tsx
Currently we bundle all of lodash, even though we use a single method of it. This increases our bundle size by at least 50KB!
- Change `import { X } from 'lodash'` to `import X from 'lodash/X'`
=> fix: stop loading the entire lodash library for a single method

src/components/Popover/PopoverContent.tsx, src/utils/useEscapeKey.tsx, src/utils/useOutsideClick.tsx
This PR is a pre-cursor to upcoming changes related to `DateInput` and `DateRangeInput`. It changes the way we define our utility hooks `useOutsideClick` and `useEscapeClick` in order to align more with the way we do stuff in the `DateRangeInput` component.
This PR shouldn't add any change to Pounce's exports, but simply re-write its internals
- Change `useOutsideClick` to accept `refs` instead of `HTMLElements` due to the way `React.Ref` lifecycle works in React, which caused bugs in some extreme use cases
- Change `useEscapeClick` to accept a `ref` instead of exposing 2 handlers to be added to a JSX element. This aligns with the way `useOutsideClick` works
- The internal modules don't have tests of their own since their functionality is always tested via the testing of …
=> Refactor internal utility hooks

src/components/DateInput/DateInput.test.tsx, src/components/DateInput/DateInput.tsx, src/components/DateInput/DateWrapper.tsx, src/components/DateInput/__snapshots__/DateInput.test.tsx.snap, src/components/DateRangeInput/DateRangeInput.test.tsx, src/components/DateRangeInput/DateRangeInput.tsx, src/components/DateRangeInput/DoubleTextInput.tsx, src/components/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap, src/components/DateRangeInput/__snapshots__/DoubleTextInput.test.tsx.snap
The `DateRangePicker` and `DateInput` components don't allow the user to close the popup, unless he/she presses the "Cancel" button. 
After user feedback, this PR changes that, allowing the user to:
- Close the popup when the user clicks outside
- Close the popup when the user presses ESC while having the popup on focus
- Toggle the popup when the calendar icon button is clicked
Whenever the popup closes, the user's selection is also reset
Closes https://github.com/panther-labs/panther/issues/1836
- Remove `icon` from input and replace with interactive `IconButton`
- Add `forwardRef` to `DateWrapper`
- Utilize `useOutsideClick` and `useESCKeypress` inside `DateRangePicker` and `DateInput`
- Update snaps
=> Aggelos daterange click outside

src/components/DateInput/DateInput.test.tsx, src/components/DateRangeInput/DateRangeInput.test.tsx, src/components/DateRangeInput/DateRangeInput.tsx
There is a small bug and the calendar doesn't close when a selection is made. This PR fixes that, making sure it closes whenever the "Apply" button is clicked
- Fix typo
- Write tests for it
=> fix: close calendar on selection application

src/components/NumberInput/NumberInput.tsx, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.test.tsx, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.tsx.snap, src/utils/helpers.test.tsx, src/utils/helpers.ts
Input labels were a bit off, raised upon values that made no sense. This PR introduces a tiny helper to accommodate empty input values (`null`, `undefined`, `''`). Even a single space can be valid though.
- Added `isEmpty` helper
- Consumed the helper for `TextInput` and `NumberInput` components.
- Added helper tests and examples.
- Visually
=> Fix raising input labels

src/components/DateInput/DateInput.mdx, src/components/DateInput/DateInput.test.tsx, src/components/DateInput/TimePicker.tsx, src/components/DateInput/__snapshots__/DateInput.test.tsx.snap, src/components/DateRangeInput/DateRangeInput.test.tsx
This one adds a new range for 24h format date pickers.
- For 24h format we are adding hours as 00 ... 23
=> fix: add hours range from 00 to 23 in 24h format

src/components/Modal/Modal.tsx
We need to have a Modal that exceeds the existing `maxWidth`
- Remove `maxWidth` from Modal
=> fix: removed maxWidth from Modal

src/components/MultiCombobox/MultiCombobox.tsx
Fixes a bug where the combo box input was rendered twice in Firefox
- Hide/Remove the duplicate input
- Locally
=> Fix duplicate combobox input

src/components/Tabs/TabList.tsx, src/components/Tabs/TabPanels.tsx
There are occasions where some tabs must be rendered conditionally thus should render null instead of children
- Added check if child is defined before cloning
- Used branch for local development
=> fix: TabList & TabPanel can accept null children

src/components/Modal/Modal.tsx, src/components/utils/ControlledAlert/ControlledAlert.tsx
Makes the `title` prop in the `Alert` optional. 
- make the  `title` prop in the `Alert` optional. 
- Allow Modal's `title` prop to receive `ReactElement`
=> feat(alert): the `title` prop is now optional

src/components/Combobox/Combobox.tsx, src/components/MultiCombobox/MultiCombobox.tsx, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap
This Pr fixes an issue where caret arrows were not retracting the dropdown modal in Combobox components. 
- Add onClick events in combobox arrows
###
Screencast
https://user-images.githubusercontent.com/15084305/116584569-29302200-a920-11eb-8dd9-360d3712ef66.mov
- locally
- npm run test
=> Collapse combobox when clicking caret

src/components/utils/Input/InputElement.tsx, src/utils/GlobalStyles.tsx
Firefox is a bit strict in order to hide the spinners, thus this PR uses the appearance property as it can be seen [here](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance) in order to prevent showing the arrows in Firefox.
- Change appearance global and inline rules.
=> Input number hide arrows for Firefox

src/components/Checkbox/Checkbox.mdx, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/useCheckboxStyles.tsx
Right now, the `Checkbox` component only accepts `selected: boolean`, but there are occasions i.e. when this checkbox is used as a select-all checkbox that we need to have a third "semi" selected state.
- Add "semi" state in Checkbox component
- Manually
=> Checkbox indeterminate state

package.json
Types are conflicting with Panther, as we have tons of TS errors from conflicting type resolutions.
- Downgrade types for `react-dom`
- npm run test
- Link and play along with Panther
=> Downgrade `@types/react-dom` in order to play along with Panther

package-lock.json, package.json
Types for `react-dom` should be strict as the `package-lock` does not get updated and creates conflicts for Panther and `reach` components.
- Make `@types/react-dom` stick to `17.0.6`
- Update `package-lock`
=> Add types as strict dependency for `react-dom`

package-lock.json, package.json
`git bisect` with the pounce dependency within Panther indicates that we should downgrade the types in order to avoid conflicts with the `@reach` packages.
- Restrict `@types/react` versioning.
=> Downgrade `@types/react` in order to play along with Panther

package-lock.json, package.json
Moving `@types/react` to https://github.com/panther-labs/pounce/blob/a91a50f3ec4164ff59524ac0f73a4474c3e55c48/package-lock.json#L3553-L3569 as working version v0.97.2
=> Downgrade `@types/react` to align with previous version working

package-lock.json, package.json
Dependencies should be aligned with `pounce v0.92` as types for `react` and `react-dom` are way off.
=> Fix: align resolutions to v0.97.2

package-lock.json, package.json
Bumping jest to v26.6.3 due to a minor vurnelability on `node-notifier`
- Bump jest to v26.6.3
- Test suite should pass
=> chore: bump jest from v26.0.1 to v26.6.3

src/components/Combobox/Combobox.test.tsx, src/components/Combobox/Combobox.tsx, src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
We always needed a way to be able to clear your selection in Comboboxes. Currently, this happens with an `ESC` keypress but that's not so obvious for users. With this PR we add an explicit way of clearing a `Combobox`'s value
https://www.figma.com/file/xJGJA3FyFcamwsjFd9rLIT/Styles-and-Components-Library?node-id=210%3A241
https://user-images.githubusercontent.com/10436045/126487401-e1739e81-2f8d-458f-b454-a067d5c5a322.mov
- Add "Clear Selection" button
- Add `withClearSelectionControl` to enable/disable this behaviour
When selecting a value, the animation that closes the menu has a "flash" of green content (due to the "clear selection" button appearing as the animation for menu closing starts). I consider this an expected side-effect and I can't think of a non-hacky way …
=> feat(combobox): add `withClearSelectionControl` prop to `Combobox`

README.md
Was poking around the docs and noticed this little typo in the README, so here's a little drive-by fix.
=> docs: fix readme typo 🙃

src/components/utils/ControlledAlert/ControlledAlert.tsx
Change ControlledAlertProps title property to `React.ReactNode` in order to avoid `@ts-ignore` when we passing title as a react node.
- Change ControlledAlertProps title property to `React.ReactNode`
- Manual
=> fix: change title type in ControlledAlertProps interface

src/components/NumberInput/NumberInput.tsx
This PR fixes a bug in our NumberInput component where the `stepUp` and `stepDown` callbacks were not updating when their dependencies get modified. 
- fix the dependency issue
- manually
=> Number input callback dependencies

src/components/Radio/Radio.mdx, src/components/Radio/Radio.tsx
Add a new prop to Radio to support [designs](https://www.figma.com/file/LkZk4NngNuOGFH3VNzS36z/08-Integrations-%E2%9C%85?node-id=2473%3A61801) 
- Add size prop to Radio
- manually
=> Add radio size

README.md, src/components/MultiCombobox/MultiCombobox.mdx, src/components/MultiCombobox/MultiCombobox.test.tsx, src/components/MultiCombobox/MultiCombobox.tsx, src/components/MultiCombobox/__snapshots__/MultiCombobox.test.tsx.snap
Looking to make an alteration to the `MultiComboBox` that matches this figma example - https://www.figma.com/proto/m8HKEVhIUX0qGaIB0geBVx/Data-Explorer-V2?page-id=0%3A1&node-id=87%3A6959&viewport=352%2C48%2C0.31&scaling=min-zoom&starting-point-node-id=84%3A5970
- Added `renderPlaceHolder` prop that allows you to pass in a custom placeholder
- Changed default `Clear All` banner button to the new design with the pleasant green icon 
- Added one test to verify custom placeholder passes properly
- Updated snapshots
=> feat: expand multicombobox props

src/components/MultiCombobox/MultiCombobox.tsx
Would like to change an implementation to also be able to leverage the `isOpen` state.  Need to expose it
- expose `isOpen` to `renderContent` function
- None needed
=> fix: pass in new function to multicombobox prop

src/components/DateInput/TimePicker.tsx
High level overview here
- remove 'clear selection' for any instance of `<TimePicker />`
Component that is updated - <img width="583" alt="image" src="https://user-images.githubusercontent.com/16771592/165838825-414afde5-6ee9-4845-ba17-49c6b7dc5646.png">
Before:
After:
=> fix: remove 'clear selection' on TimePicker

src/components/Tooltip/Tooltip.mdx, src/components/Tooltip/Tooltip.tsx
It would be nice to be able to customize the tooltip position.
Let consumers override `position`. Default to previous value.
- `npm test`
=> feat(tooltip): allow position to be set

src/components/MultiCombobox/MultiCombobox.tsx
A Sentry issue was triggered indicating a TypeError in the MultiComboBox:
[Link to Sentry Issue](https://sentry.io/organizations/panther-labs/issues/3472972234/?project=5699727&referrer=assigned_activity-email)
- Add check for `value` before checking for `value.length`
- Verify placeholder text for searchable MultiComboBox still populates as expected.
https://user-images.githubusercontent.com/4212239/183134256-b3d28a45-fbac-4835-ad4e-5025e9c1d441.mov
=> fix: type error in MultiComboBox

src/theme/icons.tsx
This PR adds the missing "expand" icon found in the Pounce design system in [Figma](https://www.figma.com/file/xJGJA3FyFcamwsjFd9rLIT/Pounce-DS-V1.0?node-id=15%3A59)
- Adds missing "expand" icon SVG path to icons.tsx
- start app locally using `npm run start`
- navigate to http://localhost:9000/#/Icon
- search for "expand"
- ensure the "expand" icon is visible
=> feat: Add "expand" icon

src/components/Box/Box.test.tsx, src/components/Box/__snapshots__/Box.test.tsx.snap, src/components/ProgressBar/ProgressBar.mdx, src/components/ProgressBar/ProgressBar.test.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap, src/system/styled.ts, src/system/utility.ts
This PR adds support for a new prop, available to all components named `backgroundOpacity`. 
This prop requires a sibling value of `backgroundColor` in order to work, so specifying a `backgroundOpacity` will only work if `backgroundColor` is also defined on the same component
Similar to how [Tailwind](https://tailwindcss.com/) implements it, we cannot rely on HTML element style parsing to "figure out" what background color an element holds. This is not only hard, but incurs a performance hit. 
```tsx
<>
<Box backgroundColor="red-100" backgroundOpacity={50} /> // equivalent to 50%
<Box backgroundColor="red-100" backgroundOpacity={0.5} /> // equivalent to 50%
<Box backgroundColor="red-100" backgroundOpacity={100} /> // equivalent to 100%
<Box backgroundColor="red-100" backgroundOpacity={1} …
```
=> [Feat] New `backgroundOpacity` prop & updated background on `ProgressBar`
